["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
MystisNFT = [
    "contracts/nft/MystisNFT.cairo",
]

MystisProxy = [
    "contracts/proxy/MystisProxy.cairo",
]

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src"]